import 'package:ecomerce_app/core/modules/products/product_model.dart';

/// Test products to be used until a data source is implemented
const DemoProducts = [
  Product(
    id: '1',
    imageUrl: 'assets/product/sandisk.jpg',
    title: 'SanDisk Cruzer Blade 64GB USB 2.0 Flash Drive',
    description: 'Manufacturer Detail: SanDisk InternationalLtd.c/o Unit 100 AirsideBusiness Park,Lakeshore Drive,Swords,Co. Dublin, Irelandmporter Details: Rashi Peripherals Pvt. Ltd. Rashi Complex,A Building,Survey186,Dongaripada,Poman Village,Vasai Bhiwandi Road, Dist. Thane,Maharastra 401208, India,Free up space on your OTG-enabled Android phone ; Pen-drive Memory Type- DDR3 SDRAM,care number:18001205899/18004195592',
    price: 15,
    availableQuantity: 20,
  ),
  Product(
    id: '2',
    imageUrl: 'assets/product/boat.jpg',
    title: 'boAt Airdopes 121v2 in-Ear True Wireless Earbuds',
    description: 'Playback- Airdopes 121v2 offers a nonstop playback of up to 3.5H with each charge and an additional 10.5H playtime with the included charging case',
    price: 13,
    availableQuantity: 5,
  ),
  Product(
    id: '3',
    imageUrl:'assets/product/mivi.jpg',
    title: 'Mivi Roam 2 Bluetooth 5W Portable Speaker',
    description: 'Small Frame. Big Sound- Roam 2 wireless speaker is designed to deliver loud and clear music by pumping out sharp trebles, detailed mids and punchy bass. Now enjoy more richer & immersive notes to fill your room with music.',
    price: 17,
    availableQuantity: 5,
  ),
  Product(
    id: '4',
    imageUrl: 'assets/product/redgear.jpg',
    title: 'Redgear MP35 Speed-Type Gaming Mousepad',
    description: 'Speed-type surface mousepad is designed with the use of great technology and craftsmanship especially for professional gamers. Non-slip rubber base',
    price: 12,
    availableQuantity: 5,
  ),
  Product(
    id: '5',
    imageUrl: 'assets/product/mouse.jpg',
    title: 'Zebronics Zeb-Transformer-M Optical USB Gaming Mouse',
    description: 'Gaming mouse: ZEB-Transformer-M premium gaming mouse is designed for gamers who want the perfect fusion of high DPI, precision gaming along with LED lights.',
    price: 12,
    availableQuantity: 10,
  ),
  Product(
    id: '6',
    imageUrl: 'assets/product/keyboard.jpg',
    title: 'Zebronics Zeb-Transformer Gaming Keyboard and Mouse Combo',
    description: 'Multicolor LED ( 4 modes - 3 light modes and 1 off mode ),Integrated media control Windows key Disable / Enable function',
    price: 12,
    availableQuantity: 10,
  ),
  Product(
    id: '7',
    imageUrl: 'assets/product/headphone.jpg',
    title: 'Redgear Cloak Wired RGB Wired Over Ear Gaming Headphones with Mic for PC',
    description: 'Sound Quality: Redgear Cloak comes equipped with 50mm Driver with Enhanced audio bass and clarity which dramatically improves your in-game sound experience. Inline Remote : No',
    price: 18,
    availableQuantity: 10,
  ),
  Product(
    id: '8',
    imageUrl: 'assets/product/joy.jpg',
    title: 'Thrustmaster T16000M FCS Hotas | Flight Game Controller | Joystick | PC',
    description: '16 action buttons with braille - style physical button identification,Exclusive precision: Hall Effect accurate technology 3D (Hall Effect) magnetic sensors located on the Stick (us patent: Us8471815)',
    price: 21,
    availableQuantity: 10,
  ),
  Product(
    id: '9',
    imageUrl:  'assets/product/jio.jpg',
    title: 'Jio Phone Black, 512 MB RAM,4 GB Memory, Black, Basic Phone (2021)',
    description: 'JIOPHONE DETAILS Buy For InexpensiveVoLTE connectivityScreen mirroring and Wi-Fi supportSupports smart Jio appsGood battery backup Beware of Poor front cameraNo touchscreenSingle SIM Verdict Reliance JioPhone stands between a featured phone and a smartphone. It has the traditional keypad design but at the same time brings some advanced features like support to VoLTE, advanced OS, and support for JIO apps',
    price: 11,
    availableQuantity: 10,
  ),
  Product(
    id: '10',
    imageUrl: 'assets/product/nokia.jpg',
    title: 'Nokia 105 Single SIM, Keypad Mobile Phone with Wireless FM Radio | Charcoal',
    description: 'All-new redesigned Nokia mobile which is familiar and easy to use,Pre-loaded games including the classic keypad mobile phone game - Pubg,freefire,COC',
    price: 11,
    availableQuantity: 10,
  ),
  Product(
    id: '11',
    imageUrl: 'assets/product/bulb.jpg',
    title: 'Philips Wiz Wi-Fi Enabled B22 9-Watt LED Smart Bulb, Compatible with Amazon Alexa and Google Assistant',
    description: 'Multi-Functional: Set Scenes, Rhythms and Schedules, dim the light and switch between millions of colours with the Wiz App.Material: Polycarbonate,Wifi Requirement: Requires a secured 2.4 GHz Wi-Fi network connection',
    price: 24,
    availableQuantity: 10,
  ),
  Product(
    id: '12',
    imageUrl: 'assets/product/dslr.jpg',
    title: 'Canon EOS 1500D 24.1 Digital SLR Camera (Black) with EF S18-55 is II Lens',
    description: 'Sensor: APS-C CMOS Sensor with 24.1 MP (high resolution for large prints and image cropping). Transmission frequency (central frequency):Frequency: 2 412 to 2 462MHz. Standard diopter :-2.5 - +0.5m-1 (dpt),Video Resolution: Full HD video with fully manual control and selectable frame rates (great for precision and high-quality video work)',
    price: 22,
    availableQuantity: 10,
  ),
  Product(
    id: '13',
    imageUrl: 'assets/product/helmet.jpg',
    title: 'Vega Verve M.Blue Helmet-S',
    description: 'High Impact ABS Material Shell,Removable and washable lining, it is also odor resistant helping the helmet stay fresher, longer in between cleaning,Metallic Quick release silent buckle',
    price: 14,
    availableQuantity: 10,
  ),
  Product(
    id: '14',
    imageUrl: 'assets/product/car.jpg',
    title: 'Bergmann Typhoon Heavy Duty Metal Car Tyre Inflator (Blue)',
    description: '[SOLID METAL BODY INFLATOR] - Unlike other plastic inflators which are delicate and noisy, Bergmann Typhoon is an all-metal. solid-build, heavy-duty, tough and reliable air inflator.',
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '15',
    imageUrl: 'assets/product/usb.jpg',
    title: 'Zebronics ZEB-90HB USB Hub',
    description: '4-Port USB 2.0 Hub. Cable length 50 cm,Useful for Laptops, PC & Computers, Mac book,Pocket Sized, Easy to Carry',
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '16',
    imageUrl: 'assets/product/science.jpg',
    title: 'Einstein Box Ultimate Science Kit',
    description: 'A SCIENCE KIT THAT HAS EVERYTHING - 100 Experiments with easy-to-follow instructions & video guides. Your kids will have hours of fun exploring this kit, just like a real scientist in a lab!',
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '17',
    imageUrl: 'assets/product/powerbank.jpg',
    title: 'MI Power Bank 3i 20000mAh Lithium Polymer 18W Fast Power Delivery Charging ',
    description: '20000mAh Lithium Polymer battery,Dual input port (Micro-USB/USB-C, Charging Time : 6.9 hours,Triple port output',
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '18',
    imageUrl: 'assets/product/powerbank.jpg',
    title: 'pTron Bullet Pro 36W PD Quick Charger ',
    description: "PTron bullet pro is a 36w charging power car charger passed the rigorous test by USB compliance standard and it's fast and safe to provides you the best possible quick charging performance",
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '19',
    imageUrl: 'assets/product/science.jpg',
    title: "Cosco Light Cricket Tennis Ball (Pack of 6) Outer Material: Rubber, Color: Green, Standard Size",
    description: 'Material rubber covered with felt,Durable,Hi bounce enjoy your game,Light weight 75 grams',
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '20',
    imageUrl: 'assets/product/20.jpg',
    title: "Acer EB321HQU 31.5 inches(80cm) 2560 x 1440 Pixels WQHD IPS Backlit LED LCD Monitor with Eye Care Features, Blue Light Filter, Flickerless, 10 Bit Color Depth (Black)",
    description: 'Exceptional IPS Display I Enjoy immaculate image quality with 2560 x 1440 Resolution Backlit LED LCD Monitor and 178 degree wide viewing angles,Eye care features : Blue light filter & Flicker-less to reduce eye fatigue,Connectivey ports includes HDMI, DVI Dual Link Up and DP ports with inbox HDMI Cable',
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '21',
    imageUrl: 'assets/product/21.jpg',
     title: "AmazonBasics 29-Piece Precision Hobby Knife Set",
    description: '29-piece hobby knife set includes a modeling knife, 26 razor-sharp blades (6x #1，4x #3，4x #4，2x #10，6x #11，4x #12), a grindstone for sharpening, and a pair of tweezers,Made of durable, high-quality alloy steel; blade styles include: stencil, fine point, scoring, and chiseling',
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '22',
    imageUrl: 'assets/product/22.jpg',
 title: "Funskool Rubik’s Cube, The Original 3x3 Colour-Matching Puzzle, Classic Problem-Solving Cube",
    description: 'The Rubik’s Cube is a classic colour-matching puzzle that can be enjoyed at home or on the move. The original, classic 3x3 cube is a highly addictive brain teaser that has fascinated fans all around the world for decades. The Rubik’s Cube features six different sides, each made up of nine colourful squares. A must for puzzle lovers, the aim is to try twist and turn the Rubik’s Cube to its original state, with every side having one solid colour. The new and improved Rubik’s Cube features a mechanism that results in a smoother, faster and more reliable play. The traditional stickers have been replaced with plastic tiles which means no fading, peeling or cheating!',
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '23',
    imageUrl: 'assets/product/23.jpg',
    title: "Game Remount Controller for Personal Computer(PC)& Laptop for Gaming",
    description: 'Games are inbuil ithe free games are inbuilt in console TV Video Game : From realistic sports Play to High-action adventures...From Classic Arcade hits to Major Movie Titles... And much more! More Options Gives You more ways to Play with lots of controller options and most sophisticated sharpshooter ever designed . And lets You team your 8-bit System with High Technology to tap into the cutting edge of video games. Most Advanced Entertainment System.... More Games Gives You Hundreds of 8-bit hits! More Excitement Spectacular Digital Sound with Real Voices. Stereo Sound Power : 12v Exclusive AC Adapter Power Consumption : Approximately -4W Models may vary as per availability',
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '24',
    imageUrl: 'assets/product/24.jpg',
 title: "FIFA 23 | Standard Edition | PS4 (PlayStation 4)",
    description: 'EA SPORTS FIFA 23 brings even more of the action and realism of football to the pitch in The World’s Game. Play the biggest tournaments in football with both the men’s and women’s FIFA World Cup tournaments coming to FIFA 23 during the season, play as women’s club teams for the first time ever, plus enjoy cross-play features that make it easier to play against friends. Enjoy a new way to play and build your dream squad in FIFA Ultimate Team with FUT Moments and a revamped Chemistry system, or live out your football dreams in Career Mode as you define your personality as a player and manage as some of football’s most famous names. In VOLTA FOOTBALL and Pro Clubs, bring more personality to the pitch with new levels of customisation and enhanced street and stadium gameplay. However you play, experience The World’s Game with over 19,000 players, 700+ teams, 100+ stadiums, and over 30 leagues - including the UEFA Champions League, Premier League, new Barclays FA Women’s Super League and France D1 Arkema with unrivalled authenticity in FIFA 23.',
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '25',
    imageUrl: 'assets/product/25.jpg',
 title: "Zebronics Zeb-Warrior 2.0 Multimedia Speaker with Aux Connectivity,USB Powered and Volume Control",
    description: 'Zeb-Warrior is a USB powered 2.0 speaker best fit for your gaming experience as it comes in a modern design and adds an element with its breathing RGB LED lights. Connect the usb side to either laptop or through adapter to any power source and another 3.5 mm pin to music source,The speaker has AUX support and comes with volume control. Bluetooth: No',
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '26',
    imageUrl: 'assets/product/26.jpg',
  title: "Simmtronics MicroSD 8GB Memory Card Class 10 with 5 Year Warranty",
    description: 'Simmtronics microSD card delivers enhanced performance with unmatched read/write speed. It makes storing and transferring high quality images, videos and files an easy task. Higher capacity micro SD card makes sure that you continue clicking amazing shots without any worry. These are perfect microSD card for Android phone and Android tablet. If you are looking for memory card for your phone, look no further. Simmtronics microSD cards are manufactured using the best technological process so that they are highly resistant to dust and heat. Its high build quality ensures reliable performance and extended durability for a longer lifespan. Simmtronics micro SD card is compatible with a wide range of phones, tablets, and motion cameras. Its high reading speed allows you to record high definition videos of long duration. It also shortens the time taken to transfer files between devices by a considerable amount.',
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '27',
    imageUrl: 'assets/product/27.jpg',
     title: "TOSHIBA Canvio Basics 2TB Portable External HDD - USB 3.0 for PC Laptop Windows and Mac, 3 Years Warranty, External Hard Drive - Black",
    description: 'Matt finish compact casing,Super speed USB 3.0 port,Easy plug-n-play operation,Built-in internal shock sensor,Country of Origin: Philippines',
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '28',
    imageUrl: 'assets/product/28.jpg',
   title: "Spigen Ultra Hybrid Back Cover Case for iPhone 14 Pro Max (TPU + Poly Carbonate | Crystal Clear)",
    description: 'Clear Design : Crystal clear transparency flaunts original phone design,Protection : Air Cushion Technology for shock absorption',
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '29',
    imageUrl: 'assets/product/29.jpg',
 title: "TRIUMPH Rival English Willow Professional Cricket BAT for Mens | Ready to Play | Light Weight with KB-222 Cricket Holdall Bag Black/Grey/RED",
    description: 'Bat Features: Hand selected and crafted for best possible combination of weight, superior grain structure high performance characteristics. Limited by the availability of suitable premium willow. Made from the best possible unbleached and naturally seasoned enlish willow,Profile : Material - English willow /wood.Minimal concaving and an explosive mid to low swell.',
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '30',
    imageUrl: 'assets/product/30.jpg',
   title: "Jaspo Slog Heavy Duty Plastic Cricket Bat,Full Size (34” X 4.5”inches) Premium Bat for All Age Groups – Kids/Boys/Girls/Adults",
    description: 'Height and Width: Jaspo Slog Cricket Bat having 34 inches height, 4.5 “inches width and 2.2 inches thickness. This Bat is Waterproof and having superior quality. Slog Bat comes in full Adult size. This bat is environment friendly and easy to carry anywhere',
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '31',
    imageUrl: 'assets/product/31.jpg',
   title: "Galaxy Star Electronics BM10 Smallest Keypad Mini Mobile Phone Dual Sim 4G with Voice Changer Colour Orange",
    description: "World's first ultra thin mobile phone Smallest mobile with( voice changer changing voice technology male voice changes to female and small childrens voice also available )dual sim facilities 2 days battery backup Low radiation, single sim, 350mah battery gsm 900/1800mhz frequency, polyphonic ringtones Alarm, 4 color options, long standby time bluetooth with dialer and fm, polyphonic ringtones, monochrome screen make and receive calls It is ultra slim and light weight (28gm). Keypad type phone Very unique and stylish I met all your friends relative would be shocked and ask you is this a real phone surprisings,special for gaming",
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '32',
    imageUrl: 'assets/product/32.jpg',
   title: "SellZone Laptop Adapter Charger for Satellite L645D",
    description: 'SellZone Laptop Adapter Charger For Toshiba Satellite L645D, L650, L650D, L655 (Power Cord Included) 19V 3.42A 65W Pin Size 5.5mm x 2.5mm',
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '33',
    imageUrl: 'assets/product/33.jpg',
   title: "ALWAFLI Waterproof Travel Electronic Gadget Organizer Case, Portable Zippered External Hard Drive Pouch for Data Cables, Chargers, Power Bank, Adapters, Phone, Plugs, Memory Card, USB (Grey)",
    description: 'Your perfect storage solutions of most electronics accessories (charger cables, USB travel plug, adapters, power banks, earphones, MP3, beauty accessories, earrings, etc.) The carrying handle allows you to easily carry this travel bag anytime, anywhere,Compartment: Travel electronics organizer Internal compartments are easily reconfigured using the 3 Velcro dividers, sort your things, 5 mesh pouches with elastic loops, hold up you cables and headphone.',
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '34',
    imageUrl: 'assets/product/34.jpg',
   title: "TOSHIBA N300 Internal 10TB NAS HDD 7200 RPM Hard Drive",
    description: 'Built For 24/7 Reliability. Toshiba’s 3.5-inch N300 NAS Hard Drive offers unprecedented reliability for NAS and other high-performance storage systems. It is optimized to meet the reliability, endurance, performance and scalability requirements of 24-hour x 7-day high-capacity storage for personal, home office and small business use. Keep your most important data safe and secure so you can move forward with confidence. The N300 is available in capacities of up to 18 TB.',
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '35',
    imageUrl: 'assets/product/35.jpg',
   title: "chenyang Cy USB 3.1 Front Panel Socket to USB 3.0 20Pin Header Male Extension Adapter for Motherboard",
    description: 'USB 3.1 Front Panel Socket to USB 3.0 20Pin Header Male Extension Adapter for Motherboard,The adapter is a converter to convert the available USB 3.0 header of a motherboard into a USB 3.1 header,Thus the USB 3.1 port of a housing can also be supplied with USB 3.1 without a suitable mainboard.',
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '36',
    imageUrl: 'assets/product/36.jpg',
   title: "CHENYANG 2P USB 3.0 Female Mount Panel to Motherboard 20pin Cable with PCI Bracket",
    description: 'You can use USB 3.0 type-A female convert USB3.0 (20pin Header) directly connected to the motherboard,Very easy to use USB3.0 data cable connected to the chassis front panel of USB3.0!',
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '37',
    imageUrl: 'assets/product/37.jpg',
   title: "Artis 507 2.0 Computer Cabinet Support Full ATX/ Micro ATX Motherboard, 1 x 8 cm Fan with VIP 400R Plus Power Supply",
    description: 'Computer Chassis Cabinet for Full ATX /Micro ATX Motherboard,0.45 mm Thickness, Steel Chassis & Matte Black Material,Air Vents / Fan Slots : 1x 12 cm Side Panel , 1 x 8cm Back Panel,PSU Position Top with 400 Watts Power Supply Included',
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '38',
    imageUrl: 'assets/product/38.jpg',
   title: "Pionic Desktop Cpu Fan With two extra legs Supports 115x Sockets | Compatible with Intel chipset Motherboard Models 915,945,965,G31,G41,G45,H55,H61,H67 | With Aluminium Heat Sink",
    description: 'This is a CPU fan compatible with Intel Chipset Motherboards Compatible with Intel chipset Motherboard Models 915,945,965,G31,G41,G45,H55,H61,H67 Supports AMD Athlon 5200+ Sockets Supports 115x sockets core Dual core i3,i5,i7 30mm Aluminum air cooling Blades, 7 blades 8cm fans, which with large air volume, and long life. No noise of fan with 6000 RPM',
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '39',
    imageUrl: 'assets/product/39.jpg',
   title: "Zebronics H61 Motherboard Intel LGA 1155 Socket | 6USB,1VGA,1LAN,1Audio,1HDMI Port",
    description: 'Processor support : Supports Intel i7/i5/i3/Pentium/Celeron processors in LGA1155 Chipset : Intel H61Chipset Memory support : 2 DDR3 dual-channel slots, Support DDR3 1066/1333/1600MHz memory LAN : Supports Realtek 8105E/8111E 100/1000 Mbps Audio : Realtek 662 3xAudio Jacks for 6 channel High definition audio Back panel : 1 PS/2 mouse/keyboard port, 1 VGA port, 1HDMI port, 4 USB 2.0 ports, 1 LAN port, 3 audio jacks On-Board connectors : 1 x Front panel connector, 1 x speaker connector, 1 x Front panel audio connector (2 x 5pin), 4 x USB 2.0 ports, 4 x SATA 3Gb/s (SATAII) ports, 1 x 4pin CPU fan connector, 1 x SYS fan connector, 1 x 24-pin ATX power connector, 1 x 4-pin ATX 12V power connector, 1 x 3pin clear CMOS header Slots : 1 PCI Express x16 slot, 1 PCI Express x1 slot',
    price: 16,
    availableQuantity: 10,
  ),
  Product(
    id: '40',
    imageUrl: 'assets/product/40.jpg',
   title: "Intel Core i5 3470 LGA 1155 Excellent Performance Processor (Silver)",
    description: "this i5 3rd gen 3470 processor supports h61 motherboard. And if you have dual core processors in branded system like Dell, HP, Lenovo you can't upgrade. But if you have i3 processor you can upgrade this i5 processor.",
    price: 16,
    availableQuantity: 10,
  ),
];

